server:
  port: 8083

spring:
  application:
    name: Workflow Relay
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          autoCreateTopics: true
        # SET CONFIG BELOW TO RESET ALL TOPIC OFFSETS
        # configuration:
        # groupId: some-unique-group-id
        # autoOffsetReset: earliest
        bindings:
          weblogout:
            consumer:
              enableDlq: true
              dlqName: weblog_dlq
              autoCommitOnError: true
              autoCommitOffset: true
          workflowindex:
            consumer:
              enableDlq: true
              dlqName: workflow_dlq
              autoCommitOnError: true
              autoCommitOffset: true
              # SET THESE PROPS TO RESET JUST ONE TOPIC'S OFFSETS
              # resetOffsets: true
              # startOffset: earliest
          taskindex:
            consumer:
              enableDlq: true
              dlqName: task_dlq
              autoCommitOnError: true
              autoCommitOffset: true
          wfmgmtworkflowindex:
            consumer:
              enableDlq: true
              dlqName: wfmgmt_dlq
              autoCommitOnError: true
              autoCommitOffset: true
          graphlog_info_debug_index:
            consumer:
              enableDlq: true
              dlqName: graphlog_info_debug_dlq
              autoCommitOnError: true
              autoCommitOffset: true
          graphlog_error_warning_index:
            consumer:
              enableDlq: true
              dlqName: graphlog_error_warning_dlq
              autoCommitOnError: true
              autoCommitOffset: true
      bindings:
        weblog:
          group: weblog
          destination: weblog
          contentType: application/json
        workflow:
          group: splitter
          destination: workflow
          contentType: application/json
        task:
          group: splitter
          destination: task
          contentType: application/json
        wfmgmt:
          group: splitter
          destination: wfmgmt
          contentType: application/json
        weblogout:
          group: splitter
          destination: weblog
          contentType: application/json
        workflowindex:
          group: index
          destination: workflow
          consumer:
            maxAttempts: 4
          contentType: application/json
        taskindex:
          group: index
          destination: task
          consumer:
            maxAttempts: 4
          contentType: application/json
        wfmgmtworkflowindex:
          group: index
          destination: wfmgmt
          consumer:
            maxAttempts: 4
          contentType: application/json
        graphlog_info_debug_index:
          group: graphlog
          destination: graphlog_info_debug
          consumer:
            maxAttempts: 4
          contentType: application/json
        graphlog_error_warning_index:
          group: graphlog
          destination: graphlog_error_warning
          consumer:
            maxAttempts: 4
          contentType: application/json

elastic:
  host: localhost
  port: 9200
  useHttps: false
  useAuthentication: false
  username: elastic
  password: testing
  workflowIndex: workflow
  taskIndex: task
  graphLogInfoDebugIndex: graphlog_info_debug
  graphLogErrorWarningIndex: graphlog_error_warning
  numberOfShards: 3
  numberOfReplicas: 2

sanitize:
  paths:
    - "metadata.parameters.api_token"
    - "metadata.parameters.example_secret"

logging:
  level:
    org:
      icgc:
        argo: DEBUG