spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        weblog:
          group: weblog
          destination: weblog
          contentType: application/json
        workflow:
          group: splitter
          destination: workflow
          contentType: application/json
        task:
          group: splitter
          destination: task
          contentType: application/json
        weblogout:
          group: splitter
          destination: weblog
          contentType: application/json
        workflowindex:
          group: index
          destination: workflow
          consumer:
            maxAttempts: 4
          contentType: application/json
        taskindex:
          group: index
          destination: task
          consumer:
            maxAttempts: 4
          contentType: application/json

elastic:
  host: localhost
  port: 9200
  workflowIndex: workflow
  taskIndex: task
