spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        weblog:
          destination: weblog
          contentType: application/json
        workflow:
          destination: workflow
          contentType: application/json
        task:
          destination: task
          contentType: application/json
        weblogout:
          destination: weblog
          contentType: application/json
        workflowindex:
          destination: workflow
          contentType: application/json
        taskindex:
          destination: task
          contentType: application/json

elastic:
  host: localhost
  port: 9200
  workflowIndex: workflow
  taskIndex: task
